---
title: "Module 4 primates"
output: html_document
---


l<-list(c("Primates

    Haplorhini
        Anthropoidea
            Platyrrhini
                Cebidae
                Atelidae
                Pitheciidae
            Catarrhini
                Cercopithecidae
                Hylobatidae
                Hominidae
        Tarsioidea
            Tarsiidae
    Strepsirhini
        Lorisoidea
            Lorisidae
            Galagidae
        Lemuroidea
            Cheirogaleidae
            Lepilemuridae
            Indriidae
            Lemuridae
            Daubentoniidae"
))

primate<-list(haplorhini, strepsirhini)
names(primate)<-c("haplorhini","strepsirhini")
#name ranks each category under the previous one

haplorhini<-list(anthropoidea, tarsioidea)
names(haplorhini)<-c("anthropoidea", "tarsioidea")

strepsirhini<-list(lorisoidea, lemuroidea)
names(strepsirhini)<-c("lorisoidea", "lemuroidea")

anthropoidea<-list(platyrrhini, catarrhini)
names(anthroidea)<-c("platyrrhini, catarrhini")

tarsioidea<-list("tarsiidae")
names(tarsioidea)<-c("tarsiidae")

lorisoidea<-list("lorisidae", "galagidae")
names(lorisoidea)<-c("lorisidae", "galagidae")

lemuroidea<-list("cheirogaleidae", "lepilemuridae", "indriidae", "lemuridae", "daubentoniidae")
names(lemuroidea)<-c("cheirogaleidae", "lepilemuridae", "indriidae", "lemuridae", "daubentoniidae")

platyrrhini<-list("cebidae", "atelidae", "pitheciidae")
names(platyrrhini)<-c("cebidae", "atelidae", "pitheciidae")

catarrhini<-list("cercopithecidae", "hylobatidae", "hominindae")
names(catarrhini)<-c("cercopithecidae", "hylobatidae", "hominindae")


l<-list(list(primate), list(haplorhini), list(anthropoidea), list(tarsioidea), list(platyrrhini), list(catarrhini), list(strepsirhini), list(lorisoidea), list(lemuroidea) )

l





s <- c("this", "is", "a", "vector", "of", "strings")
m <- matrix(data = 1:40, nrow = 5, ncol = 8)  
# this is a matrix
b <- FALSE
list <- list(s, m, b)
list
#test case

list[[2]][2, 6]
str(list)